CREATE DATABASE IF NOT EXISTS $ CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE $;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    reset_token CHAR(64) DEFAULT NULL,
    reset_expires DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id INT AUTO_INCREMENT PRIMARY KEY,
    people_count INT NOT NULL,
    special_instructions TEXT,
    id INT UNSIGNED NOT NULL,
    FOREIGN KEY (id) REFERENCES users(id)
)